### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by gsovereignty** [dolgarev/meteor-shareit#1]
I've installed and used {{>shareit}}, however nothing is rendered. This might just be me doing something wrong rather than a bug. Do I need to define any CSS classes etc? {{summary}} {{author}} and {{title} are available in the context.

Thanks!

**Comment by dolgarev** [comment]
Hello!

You have to add initialization code. For example, in the directory **lib**:

``` javascript
if (Meteor.isClient) {
  ShareIt.init({
    siteOrder: ['facebook', 'twitter'],
    sites: {
      'facebook': {
        'appId': 'YOUR_APPLICATION_ID',
        'version': 'v2.3'
      }
    },
    iconOnly: true,
    applyColors: false
  });
}
```
