### ISSUE TITLE
Is "spiderable" actually required?

### ISSUE THREAD

**Issue by fafournier** [dolgarev/meteor-shareit#5]
Is spiderable necessary to this package specifically? 
I am currently hosting my app in a PaaS that uses docker and hence require the use of alternative phantomjs-using packages such as ongoworks: spiderable. The dependency of liberation:shareit makes it impossible to work as it installs spiderable, that currently crashes with that setup. 

My hosting provider currently proposed a workaround with a fork of your package that modifies the dependency: https://github.com/Soulou/meteor-shareit/commit/9cd6e94890ab12ed36e20c1b13df146112894375

Is the spiderable necessary in "imply". It seems to me that it's just a "nice to have" that could just be mentionned in the documentation and not added in the requirements so that the user can choose which spiderable to use.

**Comment by dolgarev** [comment]
Thanks you @fafournier  for your PR. )
