### ISSUE TITLE
Facebook button : same page in new window

### ISSUE THREAD

**Issue by davidmoret** [dolgarev/meteor-shareit#7]
Hello,

I try to use your package to my sharing.
I have no problem with Twitter, however when I click on facebook share button, the same page opens in a new tab with a # appended to the end of the url. Do you recognize this behavior problem?

Thanks in advance,

David

**Comment by Perroquiet** [comment]
I'm having the same issue, how did you resolve it?

**Comment by davidmoret** [comment]
No, I did otherwise.
