### ISSUE TITLE
Unable to customise title and description (Facebook)

### ISSUE THREAD

**Issue by ritchieng** [dolgarev/meteor-shareit#9]
Hi,

I'm unable to customise a dynamic title for Facebook. Or even just a static title. 

```
shareData: function () {
    return {
      title: function() {
        if (this.data())
          return "Hello | " + this.data().title;
      },
      image: "/images/testing.png",
      thumbnail: "/images/testing.png",
      description: "Testing description."
```

My meta data are fine. But when I installed this packaged, my og tags are not configuring well.

**Comment by dolgarev** [comment]
Hello!

Field `title` cannot be a function, [see this](https://github.com/dolgarev/meteor-shareit/blob/fe2050083680c27281b612d8571296b2825db8c7/client/views/facebook/facebook.coffee#L21).

**Comment by ritchieng** [comment]
Thanks. I get it.
